# Generated by Django 5.0.3 on 2024-03-30 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeapp", "0002_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="storeapp.cart",
            ),
        ),
    ]
