# Generated by Django 5.0.3 on 2024-03-30 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storeapp", "0003_alter_cartitems_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitems",
            name="cart",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="storeapp.cart",
            ),
        ),
        migrations.AlterField(
            model_name="cartitems",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_cartitems",
                to="storeapp.product",
            ),
        ),
    ]
